<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Algorithm-1.2" data-toc-modified-id="Algorithm-1.2-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Algorithm 1.2</a></span></li><li><span><a href="#Algorithm-1.3" data-toc-modified-id="Algorithm-1.3-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Algorithm 1.3</a></span><ul class="toc-item"><li><span><a href="#Check-dimensions" data-toc-modified-id="Check-dimensions-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Check dimensions</a></span></li><li><span><a href="#Check-values" data-toc-modified-id="Check-values-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Check values</a></span></li><li><span><a href="#Build-Atilde-and-DMD-Modes" data-toc-modified-id="Build-Atilde-and-DMD-Modes-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Build Atilde and DMD Modes</a></span></li><li><span><a href="#DMD-Spectra" data-toc-modified-id="DMD-Spectra-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>DMD Spectra</a></span></li><li><span><a href="#Qualitative-comparison:-3D-view" data-toc-modified-id="Qualitative-comparison:-3D-view-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Qualitative comparison: 3D view</a></span></li><li><span><a href="#Qualitative-comparison:-2D-view" data-toc-modified-id="Qualitative-comparison:-2D-view-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Qualitative comparison: 2D view</a></span></li></ul></li><li><span><a href="#Algorithm-1.4" data-toc-modified-id="Algorithm-1.4-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Algorithm 1.4</a></span></li><li><span><a href="#Algorithm-1.5" data-toc-modified-id="Algorithm-1.5-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Algorithm 1.5</a></span></li></ul></div>

## Algorithm 1.2

In [1]:
import numpy as np

from matplotlib import cm
import matplotlib as mpl
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

from pylab import rcParams
mpl.rcParams['mathtext.fontset'] = 'cm'
mpl.rcParams['mathtext.rm'] = 'serif'
mpl.rcParams['font.family'] = 'serif'
# mpl.rcParams['font.serif'] = ['Helvetica']

# plt.style.use('seaborn-white') # use sans-serif fonts

rcParams['figure.figsize'] = 5, 5

label_size = 10
mpl.rcParams['xtick.labelsize'] = label_size
mpl.rcParams['ytick.labelsize'] = label_size
mpl.rcParams['axes.labelsize'] = 15

mpl.rcParams['axes.spines.left'] = True   ## display axis spines
mpl.rcParams['axes.spines.bottom'] = True
mpl.rcParams['axes.spines.top'] = True
mpl.rcParams['axes.spines.right'] = True
mpl.rcParams['xtick.top'] = True
mpl.rcParams['ytick.right'] = True
mpl.rcParams['xtick.direction'] = 'out'
mpl.rcParams['ytick.direction'] = 'out'
mpl.rcParams['xtick.major.size'] = 6
mpl.rcParams['ytick.major.size'] = 6
mpl.rcParams['xtick.major.width'] = 1.0
mpl.rcParams['ytick.major.width'] = 1.0


In [22]:

## Define time and space discretizations

xi = np.linspace(-10, 10, 100)
ti = np.linspace(0, 4*np.pi, 20)
dt = ti[1] - ti[0]
[xgrid, tgrid] = np.meshgrid(xi,ti)


## Create two spatio-temporal patterns
# f1 = (1/np.cosh(xgrid + 3))*(1*np.exp(1j*2.3*tgrid))
f1 = (1/np.cosh(xgrid + 3))*(1*np.exp(1j*2.5*tgrid))
# f2 = ((1/np.cosh(xgrid))*np.tanh(xgrid))*(2*np.exp(1j*2.8*tgrid))

## Combine signals and make data matrix
# f = f1 + f2
f = f1
X = f.T



In [3]:
%matplotlib

alpha_val = 1.0

fig = plt.figure(figsize = (8,8))
ax_f1 = fig.add_subplot(221, projection='3d')
ax_f2 = fig.add_subplot(222, projection='3d')
ax_f = fig.add_subplot(223, projection='3d')

ax_f1.plot_surface(xgrid.T, tgrid.T, np.real(f1.T), \
                   antialiased = False, cmap = 'gray_r', \
                   linewidth = 0, alpha = alpha_val)
# ax_f1.view_init(30,-50)
ax_f1.view_init(40,-120)

ax_f2.plot_surface(xgrid.T, tgrid.T, np.real(f2.T), \
                   antialiased = False, cmap = 'gray_r', \
                   linewidth = 0, alpha = alpha_val)
# ax_f2.view_init(30,-50)
ax_f2.view_init(40,-120)

ax_f.plot_surface(xgrid.T, tgrid.T, np.real(X), \
                  antialiased = False, cmap = 'gray_r', \
                  linewidth = 0, alpha = alpha_val)
# ax_f.view_init(30,-50)
ax_f.view_init(40,-120)

# plt.savefig('test.pdf', bbox_inches = 'tight')
plt.show()



Using matplotlib backend: MacOSX


## Algorithm 1.3

In [23]:
from numpy.linalg import svd, inv, eig

## Create DMD data matrices
X1 = X[:, 0:-1]
X2 = X[:, 1:]

## SVD and rank-2 truncation
r = 3 # rank truncation
[U, S, V] = svd(X1, full_matrices = False)
S = np.diagflat(S) # because numpy returns S as 1D array
V = np.matrix(V).H


Ur = U[:, 0:r] 
Sr = S[0:r, 0:r]

Vr = V[:, 0:r]


### Check dimensions

In [24]:
print(X1.shape, X2.shape)
print(U.shape, S.shape, V.shape)
print(Ur.shape, Sr.shape, Vr.shape)

(100, 19) (100, 19)
(100, 19) (19, 19) (19, 19)
(100, 3) (3, 3) (19, 3)


### Check values

In [30]:
print(Sr)
# print(Vr)
# print(Ur)


[[1.37149507e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.35312651e-15 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.52085382e-16]]


### Build Atilde and DMD Modes 

In [26]:

Atilde = np.dot(np.matrix(Ur).H,np.dot(X2,np.linalg.solve(Sr.T,Vr.T).T))
[D, W] = eig(Atilde)
D = np.diagflat(D)

Phi = np.dot(X2,np.dot(np.linalg.solve(Sr.T,Vr.T).T,W))  # DMD Modes



In [27]:
print(Atilde.shape, W.shape, D.shape, Phi.shape)

# print(Atilde)

# print(D)

# print(W)

# print(Phi)

print(np.matrix(Ur).H.shape)
print(X2.shape)
print(np.linalg.solve(Sr.T,Vr.T).T.shape)
print(Phi.shape)


(3, 3) (3, 3) (3, 3) (100, 3)
(3, 100)
(100, 19)
(19, 3)
(100, 3)


### DMD Spectra

In [28]:

lambda_vec = np.diag(D)
omega = np.log(lambda_vec)/dt



In [29]:

print(lambda_vec)

print(omega)


[-0.08257935+0.99658449j -0.00214431+0.00155726j  0.15468936-0.39929538j]
[-6.82597559e-16+2.5j        -8.97075925e+00+3.80030725j
 -1.28235885e+00-1.81617152j]


In [ ]:
import sys
## Compute DMD Solution
x1 = np.array(X[:, 0])
b = np.linalg.lstsq(Phi,x1, rcond = None)[0]
time_dynamics = np.zeros((r,np.size(ti)))

# print(b)

# b*np.exp(omega*ti[2])


In [ ]:
for itr in range(np.size(ti)):
    time_dynamics[:,itr] = b*np.exp(omega*ti[itr])
    
X_dmd = np.dot(Phi,time_dynamics)


In [ ]:
print(X_dmd.shape)

# print(np.iscomplex(X_dmd))

print(Phi.shape, time_dynamics.shape)

print(b.shape)

# print(X_dmd[:,0])

### Qualitative comparison: 3D view

In [ ]:
from matplotlib.colors import LightSource

plt.close('all')

alpha_val = 1.0
colormap = 'gray_r'

fig = plt.figure(figsize = (6,6))
ax_f1 = fig.add_subplot(221, projection='3d')
ax_f2 = fig.add_subplot(222, projection='3d')
ax_f = fig.add_subplot(223, projection='3d')

ls = LightSource(270, 45)

ax_f1.plot_surface(xgrid.T, tgrid.T, np.real(f1.T), \
                   antialiased = False, cmap = colormap, \
                   linewidth = 0, alpha = alpha_val)
# ax_f1.view_init(30,-50)
ax_f1.view_init(40,-120)
ax_f1.set_xlabel(r'$x$')
ax_f1.set_ylabel(r'$t$')
ax_f1.set_zlabel(r'$f_1$')
ax_f1.set_title(r'$f_1(x,t)$')


ax_f2.plot_surface(xgrid.T, tgrid.T, np.real(f2.T), \
                   antialiased = False, cmap = colormap, \
                   linewidth = 0, alpha = alpha_val)
# ax_f2.view_init(30,-50)
ax_f2.view_init(40,-120)
ax_f2.set_xlabel(r'$x$')
ax_f2.set_ylabel(r'$t$')
ax_f2.set_zlabel(r'$f_2$')
ax_f2.set_title(r'$f_2(x,t)$')


ax_f.plot_surface(xgrid.T, tgrid.T, np.real(X), \
                  antialiased = False, cmap = colormap, \
                  linewidth = 0, alpha = alpha_val)
# ax_f.view_init(30,-50)
ax_f.view_init(40,-120)
ax_f.set_xlabel(r'$x$')
ax_f.set_ylabel(r'$t$')
ax_f.set_zlabel(r'$f$')
ax_f.set_title(r'$f(x,t)$')


ax_xdmd = fig.add_subplot(224, projection='3d')

ax_xdmd.plot_surface(xgrid.T, tgrid.T, np.real(X_dmd), \
                  antialiased = False, cmap = colormap, \
                  linewidth = 0, alpha = alpha_val)
ax_xdmd.view_init(40,-120)
# ax_f.view_init(25,-135)
ax_xdmd.set_xlabel(r'$x$')
ax_xdmd.set_ylabel(r'$t$')
ax_xdmd.set_zlabel(r'$f_{\rm DMD}$',rotation = 90)
ax_xdmd.set_title(r'$f_{\rm DMD}(x,t)$')


# plt.savefig('test.pdf', bbox_inches = 'tight')
plt.show()





### Qualitative comparison: 2D view

In [ ]:

from matplotlib.colors import LightSource

text_fontsize = 20
label_size = 15
mpl.rcParams['xtick.labelsize'] = label_size
mpl.rcParams['ytick.labelsize'] = label_size
mpl.rcParams['axes.labelsize'] = 30

plt.close('all')

alpha_val = 1.0
colormap = 'gray_r'

# fig = plt.figure(figsize = (10,10))
# ax = plt.gca()
# ax_f1 = fig.add_subplot(221)
# ax_f2 = fig.add_subplot(222)
# ax_f = fig.add_subplot(223)
# ax_xdmd = fig.add_subplot(224)
fig, ax = plt.subplots(2, 2, constrained_layout=True,
                       sharex = True, sharey = True, figsize=(6,6))

ax_f1 = ax[0,0]
ax_f2 = ax[0,1]
ax_f = ax[1,0]
ax_xdmd = ax[1,1]

ls = LightSource(270, 45)

ax_f1.contourf(xgrid.T, tgrid.T, np.real(f1.T), 300, \
                   antialiased = False, cmap = colormap, \
                   alpha = alpha_val)
# ax_f1.set_xlabel(r'$x$')
ax_f1.set_ylabel(r'$t$')
ax_f1.text(5,11,r'$f_1(x,t)$',fontsize = text_fontsize)
# ax_f1.set_xticklabels([])


ax_f2.contourf(xgrid.T, tgrid.T, np.real(f2.T), 300, \
                   antialiased = False, cmap = colormap, \
                   alpha = alpha_val)
# ax_f2.set_xlabel(r'$x$')
# ax_f2.set_ylabel(r'$t$')
ax_f2.text(4,11,r'$f_2(x,t)$',fontsize = text_fontsize)
# ax_f2.set_xticklabels([])
# ax_f2.set_yticklabels([])

ax_f.contourf(xgrid.T, tgrid.T, np.real(X), 300, \
                  antialiased = False, cmap = colormap, \
                  alpha = alpha_val)
ax_f.set_xlabel(r'$x$')
ax_f.set_ylabel(r'$t$')
ax_f.text(4,11,r'$f(x,t)$',fontsize = text_fontsize)


cf = ax_xdmd.contourf(xgrid.T, tgrid.T, np.real(X_dmd), 300, \
                  antialiased = False, cmap = colormap, \
                  alpha = alpha_val)
ax_xdmd.set_xlabel(r'$x$')
# ax_xdmd.set_ylabel(r'$t$')
ax_xdmd.text(4,11,r'$f_{\rm DMD}(x,t)$',fontsize = text_fontsize)
# ax_xdmd.set_yticklabels([])

cbar = fig.colorbar(cf, ax = ax, shrink = 0.85)
# plt.savefig('../figures/output2D.png', bbox_inches = 'tight')
plt.show()




## Algorithm 1.4

In [ ]:


[U, S, V] = svd(X, full_matrices = False)
S = np.diagflat(S) # because numpy returns S as 1D array);
pc1 = U[:, 0] # first PCA mode
pc2 = U[:, 1] # second PCA mode
time_pc1 = V[:, 0] # temporal evolution of pc1
time_pc2 = V[:, 1] # temporal evolution of pc2



## Algorithm 1.5

In [ ]:
# Requires a fast ICA software package
from sklearn.decomposition import FastICA, PCA

IC = FastICA(n_components=10)
S_ = IC.fit_transform(X)  # Reconstruct signals
ICt = IC.mixing_  # Get estimated mixing matrix

ic1 = IC[0,:] # first ICA mode
ic2 = IC[1, :] # second ICA mode
time_ic1 = ICt[:,0] # temporal evolution of ic1
time_ic2 = ICt[:,1] # temporal evolution of ic2


# [IC, ICt, ~] = fastica(real(X)');
