<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#28-June-2019" data-toc-modified-id="28-June-2019-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>28-June-2019</a></span><ul class="toc-item"><li><span><a href="#Diagonalization" data-toc-modified-id="Diagonalization-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Diagonalization</a></span></li><li><span><a href="#Symmetric-matrices" data-toc-modified-id="Symmetric-matrices-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Symmetric matrices</a></span></li></ul></li><li><span><a href="#1-July-2019" data-toc-modified-id="1-July-2019-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>1-July-2019</a></span><ul class="toc-item"><li><span><a href="#Singular-value-decomposition-(SVD)" data-toc-modified-id="Singular-value-decomposition-(SVD)-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Singular value decomposition (SVD)</a></span></li></ul></li><li><span><a href="#2-July-2019" data-toc-modified-id="2-July-2019-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>2-July-2019</a></span><ul class="toc-item"><li><span><a href="#SVD-to-DMD" data-toc-modified-id="SVD-to-DMD-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>SVD to DMD</a></span></li></ul></li><li><span><a href="#4-July-2019" data-toc-modified-id="4-July-2019-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>4-July-2019</a></span><ul class="toc-item"><li><span><a href="#Least-squares" data-toc-modified-id="Least-squares-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Least squares</a></span></li><li><span><a href="#Reducing-dimensionality-with-SVD" data-toc-modified-id="Reducing-dimensionality-with-SVD-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Reducing dimensionality with SVD</a></span></li></ul></li><li><span><a href="#5-July-2019" data-toc-modified-id="5-July-2019-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>5-July-2019</a></span><ul class="toc-item"><li><span><a href="#DMD:-Overview,-Definition,-and-Algorithm" data-toc-modified-id="DMD:-Overview,-Definition,-and-Algorithm-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>DMD: Overview, Definition, and Algorithm</a></span></li></ul></li><li><span><a href="#Exercises" data-toc-modified-id="Exercises-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Exercises</a></span></li></ul></div>

# 28-June-2019

## Diagonalization

Convert the unknown problem to known problem

We do this because it converts 

$N \times N$ problem to $N$ dimensional 

So a dimensionality reduction method


- History of least squares
Gauss invented it and Legendre also made contributions

- Example from dynamical system
Lyapunov exponent are singular values


- Necessary and sufficient condition: need $N$ independent eigenvectors

- How do we get the eigenvalue problem?
\begin{equation}
A = \begin{pmatrix}
a & b \\
c & d
\end{pmatrix} \; \qquad \text{Known (given)} 
\end{equation}

\begin{equation}
\Lambda = \begin{pmatrix}
\lambda_1 & 0 \\
0 & \lambda_2
\end{pmatrix} \; \qquad \text{desire} 
\end{equation}

A general square linear system
$$A x = b$$ 


Assume an invertible matrix $P$ exists

\begin{align}
A P & = P \Lambda \\ 
P^{-1}AP & = \Lambda
\end{align}

For a $2 \times 2$ matrix $A P = P \Lambda$ gives

\begin{equation}
\begin{pmatrix}
a e_1^1 + b e_1^2  & a e_2^1 + b e_2^2 \\
c e_1^1 + d e_1^2  & c e_2^1 + d e_2^2
\end{pmatrix} = 
\begin{pmatrix}
\lambda_1 e_1^1  & \lambda_2 e_2^1 \\
\lambda_1 e_1^2  & \lambda_2 e_2^2
\end{pmatrix}
\end{equation}


This results in $A e_i = \lambda_i e_i$


## Symmetric matrices

- Orthogonal matrix is symmetric, when it is real

- Orthogonal matrix is unitary, when it is complex

- Prove the eigenvalues of real, symmetric matrix is real

- Prove the eigenvectors corresponding to distinct eigenvalues are orthogonal


Positive definite symmetric matrix, $M$, which is $N \times N$

\begin{equation}
U^T M U > 0\, , \qquad \forall \; U \in \mathbb{R}^N
\end{equation}


Eigenvalue of $2 \times 2$ matrix $A$ is 

\begin{equation}
\lambda_{1,2} = \frac{\text{tr} (A)}{2} \pm \frac{1}{2}\sqrt{\text{tr}(A)^2 - 4 \text{det}(A) }
\end{equation}


Conditions for the eigenvalues to be non-zero and distinct 


# 1-July-2019

## Singular value decomposition (SVD)



Positive semi-definite matix satisfies

1. All diagonal elements are positive
2. All eigenvalues are positive


\begin{equation}
A \in \mathbb{R}^N \times \mathbb{R}^N
\end{equation}

Symmetric
$$ A = A^T $$ 

Orthogonal
$$A^{-1} = A^T$$


__Rank-Nullity theorem__

Matrices $\underbrace{M}_{m \times n}$

\begin{align}
rank(M) + nullity (M) & = n \\
dim(I_m M) + dim(ker M) & = n
\end{align}


Domain of $\underbrace{M}_{m \times n}$ has dimension

$n$ is the dimension of the domain then it is also the column space of the $M$



__Transpose of a matrix__ (Non-square matrices)

"Swap rows with columns" $A_{ij} = A_{ji}$

$A$ and $A^T$ have the ``same eigenvalue``. (strictly true for square matrices)


$AA^T$ and $A^TA$ is symmetric

Note they are different, $AA^T$ is a $N \times N$ matrix and $A^TA$ is $M \times M$.


For non-square matrices $M_{m \times n}$, the singular value decomposition is

\begin{equation}
\underbrace{M}_{m \times n} = \underbrace{U}_{m \times m} \qquad \underbrace{\Sigma}_{m \times n} \qquad \underbrace{V^T}_{n \times n}
\end{equation}


1. Columns of $U$ are the eigenvectors of $MM^T$
2. Columns of $V$ are the eigenvectors of $M^TM$

Non-zero elements of $\Sigma$ are the square roots of the non-zero eigenvalues of $M^TM$ or $MM^T$

\begin{equation}
M = U \Sigma V^T, \qquad \underbrace{\Sigma}_{m \times n}  = \underbrace{U^T}_{m \times m} \qquad \underbrace{M}_{m \times n} \qquad \underbrace{V}_{n \times n}
\end{equation}


\begin{equation}
\Sigma = diag (\sigma_1, \ldots, \sigma_p), \qquad p = \min(m,n)
\end{equation}

$\sigma_1 \geqslant \sigma_2 \geqslant \ldots \sigma_p > 0$ are the __singular values__ of M


If $r$ is the rank of $M$, then $M$ has exactly $r$ positive singular values




# 2-July-2019

## SVD to DMD



- Four things to remember:

\begin{equation}
\underbrace{M}_{m \times n} = \underbrace{U}_{m \times m} \qquad \underbrace{\Sigma}_{m \times n} \qquad \underbrace{V^T}_{n \times n}
\end{equation}


\begin{equation}
\underbrace{\Sigma}_{m \times n}  = \underbrace{U^T}_{m \times m} \qquad \underbrace{M}_{m \times n} \qquad \underbrace{V}_{n \times n}
\end{equation}


Two equations involving $M^TM$ and $MM^T$


__Algorithm to compute SVD__

1. Compute the non-zero eigenvalues 
$\sigma_1^2 \geqslant \sigma_2^2 \geqslant \ldots \sigma_p^2 > 0, \qquad p = \min(m,n)$
corresponding eigenvectors of $M^TM$

If $p < n$ the other eigenvalues are zero

The corresponding eigenvalues 

\begin{equation}
\left[ v_1, \ldots, v_p, v_{p+1}, \ldots, v_n \right]
\end{equation}

the p columns make up $V$

2. From the form of the SVD we have

$$M V = U \Sigma$$

when $\sigma_i > 0$ (that is for $1 \leqslant i \leqslant p$)

$$ \frac{1}{\sigma_i} M V_i = U_i$$


Extend the set $u_1, \ldots, u_p$ to an orthonormal basis

$$ u_1, \ldots, u_p, \ldots, u_m$$ then

\begin{equation}
U = \left[ u_1, \ldots, u_p, u_{p+1}, \ldots, u_m \right]
\end{equation}


- Example:

\begin{equation}
\underbrace{M}_{2 \times 4} = \underbrace{U}_{2 \times 2} \qquad \underbrace{\Sigma}_{2 \times 4} \qquad \underbrace{V^T}_{4 \times 4}
\end{equation}

Let 
\begin{equation}
M = \begin{pmatrix}
1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1
\end{pmatrix}
\end{equation}

\begin{equation}
\underbrace{M}_{2 \times 4} \underbrace{M^T}_{4 \times 2} = \begin{pmatrix}
2 & 0 \\
0 & 2
\end{pmatrix}
\end{equation}


\begin{equation}
\underbrace{M^T}_{4 \times 2} \underbrace{M}_{2 \times 4} = \begin{pmatrix}
1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1 \\
1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1
\end{pmatrix}
\end{equation}

Note: both matrices above have rank 2 and eigenvalues $2,2,0,0$. ``check this claim``


\begin{equation}
\Sigma = \begin{pmatrix}
\sqrt{2} & 0 & 0 & 0 \\
0 & \sqrt{2} & 0 & 0
\end{pmatrix}
\end{equation}

Also, 
\begin{equation}
U = \begin{pmatrix}
1 & 0 \\
0 & 1
\end{pmatrix}
\end{equation}


We can calculate the matrix $V$ as 

\begin{equation}
\underbrace{M^T}_{4 \times 2} \underbrace{U}_{2 \times 2} \underbrace{\Sigma}_{2 \times 4} = \underbrace{V}_{4 \times 4} 
\end{equation}






In [5]:
import numpy as np
from numpy.linalg import svd, inv, eig


M = [[1,0,1,0],[0,1,0,1]]
[U, S, V] = svd(M, full_matrices = True)
# S = np.diagflat(S) # because numpy returns S as 1D array

print(np.size(M,0))

print(np.shape(M))
print(U)

print(S)

print(V)



2
(2, 4)
[[1. 0.]
 [0. 1.]]
[1.41421356 1.41421356]
[[ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.70710678  0.          0.70710678]
 [-0.70710678  0.          0.70710678  0.        ]
 [ 0.         -0.70710678  0.          0.70710678]]


In [8]:
# check
Sigma = np.zeros((2,4))
Sigma[0,0] = S[0]
Sigma[1,1] = S[1]

print(np.shape(Sigma))

np.dot(np.dot(U,Sigma),V)
# print(np.shape(temp))
print(np.dot(np.dot(U,Sigma),V))



(2, 4)
[[1. 0. 1. 0.]
 [0. 1. 0. 1.]]


# 4-July-2019



\begin{equation}
\underbrace{M}_{m \times n} = \underbrace{U}_{m \times m} \underbrace{\Sigma}_{m \times n} \underbrace{V^T}_{n \times n}
\end{equation}

domain $\mathbb{R}^n$ and range $\mathbb{R}^m$

rank nullity theorem

\begin{equation}
rank(\underbrace{M}_{m \times n}) + dim (ker \underbrace{M}_{m \times n}) = n
\end{equation}

__Example__:

\begin{equation}
M = \begin{pmatrix}
1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1
\end{pmatrix}
\end{equation}

here, $dim(ker \underbrace{M}_{2 \times 4}) = 2$ and hence $M$ is non-invertible



__Moore-Penrose Pseudoinverse__

\begin{equation}
\underbrace{M}_{m \times n} = \underbrace{U}_{m \times m} \underbrace{\Sigma}_{m \times n} \underbrace{V^T}_{n \times n}
\end{equation}

The inverse of $M$ defined as $M^+$

\begin{equation}
\underbrace{M^+}_{n \times m} = \underbrace{V}_{n \times n} \underbrace{\Sigma^+}_{n \times m} \underbrace{U^T}_{m \times m}
\end{equation}

$\Sigma^+$: take the reciprocal of each non-zero singular value, then take the transpose.

__Missing show $M^TM$ is close to identity__


__Example__:

Compute $\Sigma^+$ and check the product $\Sigma \Sigma^+$ for the matrix M given by

\begin{equation}
M = \begin{pmatrix}
1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1
\end{pmatrix}
\end{equation}




In [ ]:

Mplus = np.linalg.pinv(M)
print(Mplus)

[vplus,sigmaplus,uplus] = np.linalg.svd(Mplus)

print(vplus)

print(sigmaplus)

print(uplus)


## Least squares 

Solve $M x = b$ and the pseudoinverse

\begin{equation}
\underbrace{M}_{m \times n} \underbrace{x}_{n \times 1} = \underbrace{b}_{m \times 1}
\end{equation}

- Always a non-trivial kernel of $m$ and $n$ are unequal

Statement (without proof)

__Exercise__

\begin{equation}
A = \begin{pmatrix}
0 & 1\\
0 & 0
\end{pmatrix}
\end{equation}


Calculate the kernel and image of this linear map.

\begin{equation}
\hat{x}_{LS} = M^+ b
\end{equation}

this vector minimizes $|| M x - b ||^2$

$|| \cdot ||$ is the 2-norm (square root of the sum of the squares)


Construct an example where $\hat{x}$ solves $M x = b$, where $M$ is the same as above and choose $b$ to solve for $\hat{x}$. 



## Reducing dimensionality with SVD

__Truncated SVD__

Take the $k$ largest singular values, $0 < k < n$ and their corresponding eigenvectors.

\begin{equation}
\underbrace{M}_{m \times n} \approx \underbrace{U_t}_{m \times k} \underbrace{\Sigma}_{k \times k} \underbrace{V_t^T}_{k \times n} = M_t
\end{equation}

__Reduced SVD__

keep all non-zero singular values

\begin{equation}
M_r = U_r \Sigma_r V_r^T
\end{equation}


- Compute both for the matrix $M$

__DMD__: Dynamic mode reduction


``Always be mindful of the intended use and expected outcome``


- Potential use of DMD

    * Diagnostics
    
    * State estimation and future state prediction
    
    * Control
    
    




# 5-July-2019

## DMD: Overview, Definition, and Algorithm


__Data__

Data from a dynamical system

\begin{equation}
\dot{x} = f(x, t, \mu), \qquad x \in \mathbb{R}^n
\end{equation}

or discrete dynamical system $x_{k+1} = g(x_k)$


DMD constructs a proxy local(linear) dynamical system that approximates the dynamics

\begin{equation}
\frac{dx}{dt} = \mathcal{A} x
\end{equation}

where $\mathcal{A}$ 

or, for discrete time evolution $A = e^{\mathcal{A}t}$


Collection of trajectories $x_1, \ldots, x_m$ where $x_i \in \mathbb{R}^n$.

DMD produces a matrix $A$ such that

\begin{equation}
|| x_{k+1} - A x_k || 
\end{equation}

is minimized for $k = 1, \ldots, (m-1)$.

$x_1, \ldots, x_m$ are evaluated at a specific time, $\delta t$

"$m$ snapshots of the dynamical system"

Arrange the $m$ snapshots into 2 data matrices

\begin{equation}
\underbrace{X}_{n \times (m-1)} = \begin{pmatrix}
\vert & \ldots & \vert \\
x_1 & \ldots & x_{m-1} \\
\vert & \ldots & \vert
\end{pmatrix}
\end{equation}


\begin{equation}
\underbrace{X^\prime}_{n \times (m-1)} \approx \begin{pmatrix}
\vert & \ldots & \vert \\
x_2 & \ldots & x_m \\
\vert & \ldots & \vert
\end{pmatrix}
\end{equation}

such that $$X^\prime = A X$$ and this works because
\begin{equation}
\begin{pmatrix}
\vert & \ldots & \vert \\
x_2 & \ldots & x_m \\
\vert & \ldots & \vert
\end{pmatrix} = 
\begin{pmatrix}
\vert & \ldots & \vert \\
Ax_1 & \ldots & Ax_{m-1} \\
\vert & \ldots & \vert
\end{pmatrix}
\end{equation}


Traditional DMD applications have $n >> m$

We try to find the best fit $A$ to this system

\begin{equation}
A \approx X^\prime X^+
\end{equation}

where $X^+$ is the pseudo-inverse. This solution minimizes

\begin{equation}
|| X^\prime - A X ||_F 
\end{equation}

where $||\cdot||_F$ is the Frobenius norm

\begin{equation}
||X||_F = \sqrt{\Sigma_{j=1}^n \Sigma_{k=1}^m X^2_{jk}}
\end{equation}


__DMD Definition__

Suppose we have a dynamical system

\begin{equation}
\frac{dx}{dt} = f(x, t; \mu)
\end{equation}

and two sets of data $X,X^\prime$ such that

\begin{equation}
x_k^\prime = \mathcal{F}(x_k)
\end{equation}

where $\mathcal{F}(\cdot)$ is the evolution map of 

\begin{equation}
\frac{dx}{dt} = F(x,t;\mu)
\end{equation}

for time $\delta t$

DMD computes the leading eigendecomposition of the best fit linear operator $A$ relating the data 

\begin{equation}
X^\prime \approx A X, \qquad A = X^\prime X^+
\end{equation}

where $X^+$ 

The DMD modes, also called dynamic modes, are the eigenvectors of $A$ and each DMD mode corresponds to the particular eigenvalue of $A$.


# Exercises