<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#8-July-2019" data-toc-modified-id="8-July-2019-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>8-July-2019</a></span><ul class="toc-item"><li><span><a href="#Examples" data-toc-modified-id="Examples-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Examples</a></span></li><li><span><a href="#Singular-value-decomposition" data-toc-modified-id="Singular-value-decomposition-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Singular value decomposition</a></span></li><li><span><a href="#Reduced-SVD" data-toc-modified-id="Reduced-SVD-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Reduced SVD</a></span></li><li><span><a href="#Eigendecomposition-and-SVD" data-toc-modified-id="Eigendecomposition-and-SVD-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Eigendecomposition and SVD</a></span></li><li><span><a href="#Dynamic-Mode-Decomposition" data-toc-modified-id="Dynamic-Mode-Decomposition-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Dynamic Mode Decomposition</a></span></li><li><span><a href="#Application-of-DMD-to-the-time-dependent-double-gyre" data-toc-modified-id="Application-of-DMD-to-the-time-dependent-double-gyre-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Application of DMD to the time dependent double-gyre</a></span></li></ul></li><li><span><a href="#9-July-19" data-toc-modified-id="9-July-19-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>9-July-19</a></span><ul class="toc-item"><li><span><a href="#Review-and-discussion-of-DMD" data-toc-modified-id="Review-and-discussion-of-DMD-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Review and discussion of DMD</a></span></li><li><span><a href="#Exercise" data-toc-modified-id="Exercise-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Exercise</a></span></li></ul></li></ul></div>

# 8-July-2019

## Examples

__Diagonalization__ 

\begin{equation}
A = \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
\end{equation}


1. Condition $A = A^T$

2. eigenvalues are real

3. eigenvectors are orthogonal

4. condition for $A$ to be positive definite symmetric
    a. Diagonal elements are positive
    
    b. eigenvalues are positive

5. $A = (1, 2)$
    a. Compute $A A^T$, $A^T A$
    b. Compute eigenvalues of each



## Singular value decomposition

\begin{equation}
\underbrace{M}_{m \times n} = \underbrace{U_t}_{m \times m} \underbrace{\Sigma}_{m \times n} \underbrace{V^T}_{n \times n}
\end{equation}


Using 
\begin{equation}
M = \begin{pmatrix}
1 & 0 & 1 & 0\\
0 & 1 & 0 & 1
\end{pmatrix}
\end{equation}

1. Compute the pseudoinverse of $M, M^+$

2. Show $\hat{x} = M^+ b$ minimizes $||M x - b||$

3. Discuss the relationship between singular values and rank



## Reduced SVD

\begin{equation}
M V_r = U_r \Sigma_r
\end{equation}

``remove all parts that produce zeros``

__missing equation__


where $p$ is the number of non-zero singular values.

Q. In what sense does the reduced SVD approximate the full SVD?





## Eigendecomposition and SVD

ED
\begin{align}
\underbrace{M}_{n \times n} \underbrace{P}_{n \times n}  = P \Lambda  \; M = P \Lambda P^{-1}
\end{align}

SVD
\begin{align}
\underbrace{M}_{m \times n} \underbrace{V}_{n \times n}  = \underbrace{U}_{m \times m} \underbrace{\Sigma}_{m \times n} \; M = U \Sigma V^T
\end{align}

__Example__

Compute SVD and ED for the following matrices

\begin{equation}
\begin{pmatrix}
2 & 1\\
1 & 2
\end{pmatrix}
\end{equation}

\begin{equation}
\begin{pmatrix}
1 & 1\\
1 & 1
\end{pmatrix}
\end{equation}

In [1]:
import numpy as np
from numpy.linalg import eig, svd

m1 = [[2,1],[1,2]]

[D, W] = eig(np.dot(m1,np.transpose(m1)))
print(np.sqrt(D))
print(W)

[U,Sigma,V] = svd(m1)
print(U,Sigma,V)


m2 = [[1,1],[1,1]]

[D, W] = eig(np.dot(m2,np.transpose(m2)))
print(np.sqrt(D))
print(W)

[U,Sigma,V] = svd(m2)
print(U,Sigma,V)


[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]] [3. 1.] [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[2.00000000e+00 2.10734243e-08]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]] [2.00000000e+00 3.35470445e-17] [[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


In [11]:

np.dot(V,np.transpose(V))


array([[ 1.00000000e+00, -1.01465364e-17],
       [-1.01465364e-17,  1.00000000e+00]])


## Dynamic Mode Decomposition

More details of the set-up

1. $m$ snapshots of data at $m-1$ intervals of time

$$\Delta t, 2 \Delta t, 3 \Delta t, \ldots, (m-1)\Delta t$$ 

or 

$$k \Delta t, k = 1, \ldots, (m-1)$$

Data is represented as $n \times 1$ column vector, $x(t)$, 

$$x_k = x(k \Delta t)$$

\begin{equation}
\underbrace{X}_{n \times (m-1)} = \begin{pmatrix}
\vert & \ldots & \vert \\
x_1 & \ldots & x_{m-1} \\
\vert & \ldots & \vert
\end{pmatrix}
\end{equation}

\begin{equation}
\underbrace{X^\prime}_{n \times (m-1)} \approx \begin{pmatrix}
\vert & \ldots & \vert \\
x_2 & \ldots & x_m \\
\vert & \ldots & \vert
\end{pmatrix}
\end{equation}

Crucial step 

Each matrix is $n \times (m-1)$, generally $n >> m$.

such that $$X^\prime = A X$$

where $\underbrace{A}_{n \times n}$ is the evolution operator.


## Application of DMD to the time dependent double-gyre 


Q. How does the DMD respect the periodicity?


Start with time independent case

1. Given the trajectories at the stagnation point and separatrices, what information does DMD give us?

Start with time-dependent case

2. How can the separatrices be extracted using DMD?


__Exercise__

Double-gyre streamfunction: time-independent and time-dependent





# 9-July-19

## Review and discussion of DMD

\begin{equation}
\underbrace{X}_{n \times (m-1)} = \begin{pmatrix}
\vert & \ldots & \vert \\
x_1 & \ldots & x_{m-1} \\
\vert & \ldots & \vert
\end{pmatrix}
\end{equation}

\begin{equation}
\underbrace{X^\prime}_{n \times (m-1)} \approx \begin{pmatrix}
\vert & \ldots & \vert \\
x_2 & \ldots & x_m \\
\vert & \ldots & \vert
\end{pmatrix}
\end{equation}

Columns are data snapshots

DMD - generates the "fake dynamics"

\begin{equation}
X^\prime \approx A X
\end{equation}

where $A$ is the linear autonomous dynamics

1. In what sense does the "fake dynamics" approximate the "real dynamics"?

2. Autonomous and non-autonomous dynamics are "very different"


__DMD Algorithm__


1. Compute the reduced SVD approximation to $X$

\begin{equation}
\underbrace{X}_{n \times (m-1)} \approx \underbrace{U}_{n \times r} \underbrace{\Sigma}_{r \times r} \underbrace{V^*}_{r \times (m-1)}
\end{equation}

$r$ is the rank of the reduced SVD approximation to $X$

__Exercise__

\begin{equation}
M = \begin{pmatrix}
0 & -1 \\
1 & 0
\end{pmatrix}
\end{equation}


Idea: The modes corresponding to the non-zero singular values represent structure in the data


Left singular values of $U$ are referred to as the POD modes


2. $A$ is obtained using the pseudoinverse of $X$

\begin{equation}
\underbrace{A}_{n \times n} = \underbrace{X}_{n \times (m-1)} \underbrace{V}_{(m-1) \times r} \underbrace{\Sigma^{-1}}_{r \times r} \underbrace{U^*}_{r \times n} 
\end{equation}

In practice, it is more computationally efficient to compute $\tilde{A}$, the $r \times r$ projection of $A$ onto the POD modes.

\begin{equation}
\underbrace{\tilde{A}}_{r \times r} = \underbrace{U^*}_{r \times n} \underbrace{A}_{n \times n} \underbrace{U}_{n \times r} = \underbrace{U^*}_{r \times n} \underbrace{X}_{n \times (m-1)}  \underbrace{V}_{(m-1) \times r}  \underbrace{\Sigma^{-1}}_{r \times r} \underbrace{U^*}_{r \times n} \underbrace{U}_{n \times r}
\end{equation}


$\tilde{A}$ defines the low dimensional linear model 

\begin{equation}
\underbrace{\tilde{x}_{k+1}}_{r \times 1} = \underbrace{\tilde{A}}_{r \times r} \underbrace{\tilde{x}_k}_{r \times 1}
\end{equation}


reconstruct high dimensional states.


3. Compute the eigendecomposition of $\underbrace{\tilde{A}}_{r \times r}$

\begin{equation}
\underbrace{\tilde{A}}_{r \times r} \underbrace{W}_{r \times r} = \underbrace{W}_{r \times r} \underbrace{\Lambda}_{r \times r}
\end{equation}


4. Construct the eigendecomposition of $A$ from $W$ and $\Lambda$

Eigenvectors of $A$ (DMD modes) are given by the columns of $\Phi$.

\begin{equation}
\underbrace{\Phi}_{n \times r} = \underbrace{X^\prime}_{n \times (m-1)} \underbrace{V}_{(m-1) \times r} \underbrace{\Sigma^{-1}}_{r \times r} \underbrace{W}_{r \times r}
\end{equation}


__Potential reason for limitations of DMD__: (see section 1.5 in the book)

- What are the connections between DMD and dimensionality reduction obtained from center manifold theory?





## Exercise

In [2]:

## Singular values of M are equal to the eigenvalues of M^T M and MM^T

M = [[0,-1],[1,0]]


[D,W] = eig(M)
print(D,W)

[D,W] = eig(np.dot(M,np.transpose(M)))
print(D,W)

[U,Sigma,V] = svd(M)
print(U,Sigma,V)


[0.+1.j 0.-1.j] [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]
[1. 1.] [[1. 0.]
 [0. 1.]]
[[ 0. -1.]
 [-1.  0.]] [1. 1.] [[-1. -0.]
 [ 0.  1.]]
