<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#28-June-2019" data-toc-modified-id="28-June-2019-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>28-June-2019</a></span><ul class="toc-item"><li><span><a href="#Diagonalization" data-toc-modified-id="Diagonalization-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Diagonalization</a></span></li><li><span><a href="#Symmetric-matrices" data-toc-modified-id="Symmetric-matrices-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Symmetric matrices</a></span></li></ul></li><li><span><a href="#1-July-2019" data-toc-modified-id="1-July-2019-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>1-July-2019</a></span><ul class="toc-item"><li><span><a href="#Singular-value-decomposition-(SVD)" data-toc-modified-id="Singular-value-decomposition-(SVD)-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Singular value decomposition (SVD)</a></span></li></ul></li><li><span><a href="#2-July-2019" data-toc-modified-id="2-July-2019-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>2-July-2019</a></span><ul class="toc-item"><li><span><a href="#SVD-to-DMD" data-toc-modified-id="SVD-to-DMD-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>SVD to DMD</a></span></li></ul></li></ul></div>

# 28-June-2019

## Diagonalization

Convert the unknown problem to known problem

We do this because it converts 

$N \times N$ problem to $N$ dimensional 

So a dimensionality reduction method


- History of least squares
Gauss invented it and Legendre also made contributions

- Example from dynamical system
Lyapunov exponent are singular values


- Necessary and sufficient condition: need $N$ independent eigenvectors

- How do we get the eigenvalue problem?
\begin{equation}
A = \begin{pmatrix}
a & b \\
c & d
\end{pmatrix} \; \qquad \text{Known (given)} 
\end{equation}

\begin{equation}
\Lambda = \begin{pmatrix}
\lambda_1 & 0 \\
0 & \lambda_2
\end{pmatrix} \; \qquad \text{desire} 
\end{equation}

A general square linear system
$$A x = b$$ 


Assume an invertible matrix $P$ exists

\begin{align}
A P & = P \Lambda \\ 
P^{-1}AP & = \Lambda
\end{align}

For a $2 \times 2$ matrix $A P = P \Lambda$ gives

\begin{equation}
\begin{pmatrix}
a e_1^1 + b e_1^2  & a e_2^1 + b e_2^2 \\
c e_1^1 + d e_1^2  & c e_2^1 + d e_2^2
\end{pmatrix} = 
\begin{pmatrix}
\lambda_1 e_1^1  & \lambda_2 e_2^1 \\
\lambda_1 e_1^2  & \lambda_2 e_2^2
\end{pmatrix}
\end{equation}


This results in $A e_i = \lambda_i e_i$


## Symmetric matrices

- Orthogonal matrix is symmetric, when it is real

- Orthogonal matrix is unitary, when it is complex

- Prove the eigenvalues of real, symmetric matrix is real

- Prove the eigenvectors corresponding to distinct eigenvalues are orthogonal


Positive definite symmetric matrix, $M$, which is $N \times N$

\begin{equation}
U^T M U > 0\, , \qquad \forall \; U \in \mathbb{R}^N
\end{equation}


Eigenvalue of $2 \times 2$ matrix $A$ is 

\begin{equation}
\lambda_{1,2} = \frac{\text{tr} (A)}{2} \pm \frac{1}{2}\sqrt{\text{tr}(A)^2 - 4 \text{det}(A) }
\end{equation}


Conditions for the eigenvalues to be non-zero and distinct 


# 1-July-2019

## Singular value decomposition (SVD)



Positive semi-definite matix satisfies

1. All diagonal elements are positive
2. All eigenvalues are positive


\begin{equation}
A \in \mathbb{R}^N \times \mathbb{R}^N
\end{equation}

Symmetric
$$ A = A^T $$ 

Orthogonal
$$A^{-1} = A^T$$


__Rank-Nullity theorem__

Matrices $\underbrace{M}_{m \times n}$

\begin{align}
rank(M) + nullity (M) & = n \\
dim(I_m M) + dim(ker M) & = n
\end{align}


Domain of $\underbrace{M}_{m \times n}$ has dimension

$n$ is the dimension of the domain then it is also the column space of the $M$



__Transpose of a matrix__ (Non-square matrices)

"Swap rows with columns" $A_{ij} = A_{ji}$

$A$ and $A^T$ have the ``same eigenvalue``. (strictly true for square matrices)


$AA^T$ and $A^TA$ is symmetric

Note they are different, $AA^T$ is a $N \times N$ matrix and $A^TA$ is $M \times M$.


For non-square matrices $M_{m \times n}$, the singular value decomposition is

\begin{equation}
\underbrace{M}_{m \times n} = \underbrace{U}_{m \times m} \qquad \underbrace{\Sigma}_{m \times n} \qquad \underbrace{V^T}_{n \times n}
\end{equation}


1. Columns of $U$ are the eigenvectors of $MM^T$
2. Columns of $V$ are the eigenvectors of $M^TM$

Non-zero elements of $\Sigma$ are the square roots of the non-zero eigenvalues of $M^TM$ or $MM^T$

\begin{equation}
M = U \Sigma V^T, \qquad \underbrace{\Sigma}_{m \times n}  = \underbrace{U^T}_{m \times m} \qquad \underbrace{M}_{m \times n} \qquad \underbrace{V}_{n \times n}
\end{equation}


\begin{equation}
\Sigma = diag (\sigma_1, \ldots, \sigma_p), \qquad p = \min(m,n)
\end{equation}

$\sigma_1 \geqslant \sigma_2 \geqslant \ldots \sigma_p > 0$ are the __singular values__ of M


If $r$ is the rank of $M$, then $M$ has exactly $r$ positive singular values




# 2-July-2019

## SVD to DMD



- Four things to remember:

\begin{equation}
\underbrace{M}_{m \times n} = \underbrace{U}_{m \times m} \qquad \underbrace{\Sigma}_{m \times n} \qquad \underbrace{V^T}_{n \times n}
\end{equation}


\begin{equation}
\underbrace{\Sigma}_{m \times n}  = \underbrace{U^T}_{m \times m} \qquad \underbrace{M}_{m \times n} \qquad \underbrace{V}_{n \times n}
\end{equation}


Two equations involving $M^TM$ and $MM^T$


__Algorithm to compute SVD__

1. Compute the non-zero eigenvalues 
$\sigma_1^2 \geqslant \sigma_2^2 \geqslant \ldots \sigma_p^2 > 0, \qquad p = \min(m,n)$
corresponding eigenvectors of $M^TM$

If $p < n$ the other eigenvalues are zero

The corresponding eigenvalues 

\begin{equation}
\left[ v_1, \ldots, v_p, v_{p+1}, \ldots, v_n \right]
\end{equation}

the p columns make up $V$

2. From the form of the SVD we have

$$M V = U \Sigma$$

when $\sigma_i > 0$ (that is for $1 \leqslant i \leqslant p$)

$$ \frac{1}{\sigma_i} M V_i = U_i$$


Extend the set $u_1, \ldots, u_p$ to an orthonormal basis

$$ u_1, \ldots, u_p, \ldots, u_m$$ then

\begin{equation}
U = \left[ u_1, \ldots, u_p, u_{p+1}, \ldots, u_m \right]
\end{equation}


- Example:

\begin{equation}
\underbrace{M}_{2 \times 4} = \underbrace{U}_{2 \times 2} \qquad \underbrace{\Sigma}_{2 \times 4} \qquad \underbrace{V^T}_{4 \times 4}
\end{equation}

Let 
\begin{equation}
M = \begin{pmatrix}
1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1
\end{pmatrix}
\end{equation}

\begin{equation}
\underbrace{M}_{2 \times 4} \underbrace{M^T}_{4 \times 2} = \begin{pmatrix}
2 & 0 \\
0 & 2
\end{pmatrix}
\end{equation}


\begin{equation}
\underbrace{M^T}_{4 \times 2} \underbrace{M}_{2 \times 4} = \begin{pmatrix}
1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1 \\
1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1
\end{pmatrix}
\end{equation}

Note: both matrices above have rank 2 and eigenvalues $2,2,0,0$. ``check this claim``


\begin{equation}
\Sigma = \begin{pmatrix}
\sqrt{2} & 0 & 0 & 0 \\
0 & \sqrt{2} & 0 & 0
\end{pmatrix}
\end{equation}

Also, 
\begin{equation}
U = \begin{pmatrix}
1 & 0 \\
0 & 1
\end{pmatrix}
\end{equation}


We can calculate the matrix $V$ as 

\begin{equation}
\underbrace{M^T}_{4 \times 2} \underbrace{U}_{2 \times 2} \underbrace{\Sigma}_{2 \times 4} = \underbrace{V}_{4 \times 4} 
\end{equation}






In [28]:
import numpy as np
from numpy.linalg import svd, inv, eig


M = [[1,0,1,0],[0,1,0,1]]
[U, S, V] = svd(M, full_matrices = True)
# S = np.diagflat(S) # because numpy returns S as 1D array

print(np.shape(M))
print(U)

print(S)

print(V)

(2, 4)
[[1. 0.]
 [0. 1.]]
[1.41421356 1.41421356]
[[ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.70710678  0.          0.70710678]
 [-0.70710678  0.          0.70710678  0.        ]
 [ 0.         -0.70710678  0.          0.70710678]]


In [29]:
# check
Sigma = np.zeros((2,4))
Sigma[0,0] = S[0]
Sigma[1,1] = S[1]

np.dot(np.dot(U,Sigma),V.T)
print(np.shape(temp))
print(np.dot(np.dot(U,Sigma),V.T))



(2, 4)
[[ 1.  0. -1.  0.]
 [ 0.  1.  0. -1.]]
